stages:
  - build
  - test

default:
  image: debian:latest
  before_script:
    - apt update && apt install -y curl git git-lfs
    - curl -sL https://taskfile.dev/install.sh | sh
    - mv ./bin/task /usr/local/bin/task
    - git lfs install
    - git lfs pull

buildLinuxARM:
  stage: build
  script:
    - task LinuxARM
  artifacts:
    paths:
      - target/LinuxARM

buildLinuxAMD:
  stage: build
  script:
    - task Linux32
    - task Linux64
  artifacts:
    paths:
      - target/Linux32
      - target/Linux64

buildWinAMD:
  stage: build
  script:
    - task Win32
    - task Win64
  artifacts:
    paths:
      - target/Win32
      - target/Win64

test:
  stage: test
  script:
    - task test
