stages:
  - build
  - test

default:
  image: debian:latest
  before_script:
    - echo "Before script"
    - apt update
    - apt install make -y

buildLinuxARM:
  stage: build
  script:
    - make LinuxARM
  cache:
    paths:
      - target/LinuxARM
  artifacts:
    paths:
      - target/LinuxARM

buildLinuxAMD:
  stage: build
  script:
    - make Linux32
    - make Linux64
  cache:
    paths:
      - target/Linux32
      - target/Linux64
  artifacts:
    paths:
      - target/Linux32
      - target/Linux64

buildWinAMD:
  stage: build
  script:
    - make Win32
    - make Win64
  cache:
    paths:
      - target/Win32
      - target/Win64
  artifacts:
    paths:
      - target/Win32
      - target/Win64

test:
  stage: test
  script:
    - echo "Tests are starting:"
    - make test
